import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js App - About",
  description: "Generated by create next app",
};

export default function AboutLayout({ children } : { children: React.ReactNode }) {
    return (
        <div>
            <h1>About Layout</h1>
            {children}
        </div>
    );  
    
}